default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  port: 5432

development:
  <<: *default
  database: sotsugyo_seisaku_development

test:
  <<: *default
  database: sotsugyo_seisaku_test
