default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  pool: 5
  username: postgres
  password: password
  port: 5432

development:
  <<: *default
  database: sotsugyo_seisaku_development

test:
  <<: *default
  database: sotsugyo_seisaku_test

production:
  <<: *default
  database: sotsugyo_seisaku_production
  url: <%= ENV['DATABASE_URL'] %>

  # 追加：cache用の設定
  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>